### ISSUE TITLE
Calculate service height metric

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-analytics-java#31]
Calculate service height metric for each service in a trace. Choose the highest value for the metric and label metric with service name

Service height: number of service hops from a service to leaf service
Service depth: number of service hops from a service to root service

**Comment by yurishkuro** [comment]
Suggestion: each new metric should have a blurb describing why it's useful, which problems can be solved by knowing that metric.

**Comment by pavolloffay** [comment]
+1. This would be very useful. Some of these metrics might not be useful. 

Do you have any suggestions how this metric could be useful? This might help when SLAs are being defined.
