### ISSUE TITLE
Calculate metric for number of errors per service

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-analytics-java#32]

**Comment by christian-morin** [comment]
Is this verified? Generated a few error spans which can be viewed by tag error=true, but the Prometheus value for the Spark job is still empty:
```
# HELP errors_total Number of errors split by service and operation name
# TYPE errors_total counter
# HELP service_parents_total Service parents - number of services directly calling a service
```
All other values correctly populated though

**Comment by pavolloffay** [comment]
Which spark job are you running?

**Comment by christian-morin** [comment]
Well, testing the entire Spark suite from this project :) But noticed some Spans not being picked up by the NumberOfErrors calculation.

Ran some tests and located the problem to some implementations setting the tag to boolean true and others to the String "true". The project only assumes String values.

Changing the calculate method to:

```
/**
   * @return error spans within a graph.
   */
  public static Set<Span> calculate(Graph graph) {
    TraceTraversal<Vertex, Vertex> errorSpansTraversal = graph.traversal(TraceTraversalSource.class)
        .hasTagWithValues(Tags.ERROR.getKey(), "true", Boolean.TRUE);
```

Fixes the issue. In order for the tests etc to work around this, the Span has to be changed to allow for Object values (and cast to/from Object to String for other implementations already assuming only String values).

Not sure if it's a great idea? Or if implementations actually should only use String values?
