### ISSUE TITLE
README for Jupyter directory

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-analytics-java#51]
Currently, the only documentation we seem to have for the Jupyter directory is this blog post:

https://medium.com/jaegertracing/jaeger-data-analytics-with-jupyter-notebooks-b094fa7ab769

It would be great to have a readme file on how to get started with the current notebooks, and/or how to create new notebooks.

**Comment by shreyagupta30** [comment]
Hi @jpkrohling ! I would love to take up this issue. Thanks :)

**Comment by yurishkuro** [comment]
what about https://github.com/jaegertracing/jaeger-analytics-java#run-jupyter-as-docker ?
