### ISSUE TITLE
io.jaegertracing.analytics.model.Converter limits span durations to durations shorter than 1 second

### ISSUE THREAD

**Issue by alefhar** [jaegertracing/jaeger-analytics-java#55]
To convert from protobuf `io.jaegertracing.api_v2.Model.Span` to `io.jaegertracing.analytisc.model.Span` the class `io.jaegertracing.analytics.model.Converter` offers a utility method `Span toSpan(Model.Span)` which extracts and converts the data from the protobuf `Model.Span` and writes it to a custom `Span` which is later used to create a graph.

It seems, however, that `toSpan()` only copies the nano second fraction of the duration and completely ignores the `seconds` data field. 
```
span.durationMicros = protoSpan.getDuration().getNanos() / 1000;
```
From the [documentation](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#google.protobuf.Duration) a duration consists of a `seconds` part and a `nanos` part. The latter representing a fraction of a second at nanosecond resolution in the range -999,999,999 to +999,999,999 inclusive. `nanos` can only store durations less than a second.
The same applies to `Timestamp` and any code that considers only the `nanos` part of a `Timestamp`.

Can you confirm, that this is an issue?

**Comment by alefhar** [comment]
@yurishkuro Is it possible to create a new release with this change. If not, when is the next release scheduled?
Thanks

**Comment by yurishkuro** [comment]
I tagged the release, but the push to sonatype failed. I am not familiar with the release process, spent like 20min trying to get it working manually, no luck.  cc @pavolloffay
